# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, ‘8.0’
use_frameworks!

target ‘teste99’ do

pod 'Realm’
pod 'Mantle’
pod 'AFNetworking', '~> 2.5'

end

target 'teste99Tests' do

end



